FROM node:20

# Create and set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY ./dexscreener/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY ./dexscreener .

# Expose the port on which your Express.js application is running
EXPOSE 3000

# Command to run your application
CMD ["node", "main.js"]